name: Docs Tests
on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    types: [opened, synchronize, labeled]

concurrency:
  group: ci-docs-tests-${{ github.ref }}  # branch or tag name
  cancel-in-progress: true

env:
  DEFAULT_PYTHON_VERSION: '3.9'

jobs:
  changes:
    name: Check for file changes
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v3
      - uses: RasaHQ/pr-changed-files-filter@c4f7116a04b8a4596313469429e2ad235f59d9c4
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/change_filters.yml

  test_documentation:
    name: Test Documentation
    runs-on: ubuntu-latest
    needs: [ changes ]
    if: needs.changes.outputs.docs == 'true'

    steps:
    - name: Checkout git repository 🕝
      uses: actions/checkout@v3

    - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }} 🐍
      uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6  # v3.0
      with:
        python-version: ${{ env.DEFAULT_PYTHON_VERSION }}

    - name: Set up Node 12.x 🦙
      uses: actions/setup-node@v3.3.0
      with:
        node-version: '12.x'

    - name: Read Poetry Version 🔢
      run: |
        echo "POETRY_VERSION=$(scripts/poetry-version.sh)" >> $GITHUB_ENV
      shell: bash

    - name: Install poetry 🦄
      uses: Gr1N/setup-poetry@09236184f6c1ab47c0dc9c1001c7fe200cf2afb0 # v7
      with:
        poetry-version: ${{ env.POETRY_VERSION }}

    - name: Load Poetry Cached Libraries ⬇
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ env.POETRY_VERSION }}-${{ env.DEFAULT_PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ secrets.POETRY_CACHE_VERSION }}
        restore-keys: ${{ runner.os }}-poetry-${{ env.DEFAULT_PYTHON_VERSION }}

    - name: Clear Poetry cache
      if: steps.cache-poetry.outputs.cache-hit == 'true' && contains(github.event.pull_request.labels.*.name, 'tools:clear-poetry-cache-docs-tests')
      run: rm -r .venv

    - name: Create virtual environment
      if: (steps.cache-poetry.outputs.cache-hit != 'true' || contains(github.event.pull_request.labels.*.name, 'tools:clear-poetry-cache-docs-tests'))
      run: python -m venv create .venv

    - name: Set up virtual environment
      if: needs.changes.outputs.docs == 'true'
      run: poetry config virtualenvs.in-project true

    - name: Load Yarn Cached Packages ⬇
      uses: actions/cache@v3
      with:
        path: docs/node_modules
        key: ${{ runner.os }}-yarn-12.x-${{ hashFiles('docs/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-12.x

    - name: Install Dependencies 📦
      run: |
        sudo apt-get -y install libpq-dev
        make install-full install-docs

    - name: Run Swagger 🕵️‍♀️
      run: |
        npm install -g swagger-cli
        swagger-cli validate docs/static/spec/action-server.yml
        swagger-cli validate docs/static/spec/rasa.yml

    - name: Test Docs 🕸
      run: make test-docs
