# This is a installation test that we run daily. We attempt to install Rasa
# on Ubuntu, Mac and Windows and try to run `rasa init`. The goal here is to
# catch installation issues in an automated way.

name: Cron Test to Check Pip Installation

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-latest, windows-2019, windows-2022]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@2c3dd9e7e29afd70cc0950079bde6c979d1f69f9  # v3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Try to install Rasa.
      run: |
        python -m pip install rasa
    - name: Try to install Rasa[full].
      run: |
        python -m pip install rasa[full]
    - name: Try to run Rasa.
      run: |
        python -m rasa --version
        # Must create a folder first
        mkdir rasa-demo
        # Next we try to init. 
        python -m rasa init --init-dir rasa-demo --no-prompt
    - name: Notify slack on failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@212e9f7a9ca33368c8dd879d6053972128258985
      with:
        channel_id: ${{ secrets.SLACK_ALERTS_CHANNEL_ID }}
        status: FAILED
        color: danger
